"""Model applicability registry for QuantVerse global research."""

from __future__ import annotations

import importlib.util

import pandas as pd


def model_applicability_matrix() -> pd.DataFrame:
    """Return a deterministic model applicability matrix."""
    rows = [
        _row(
            "Equal Weight",
            "portfolio",
            "returns matrix",
            "weights",
            "CAGR/Sharpe/drawdown",
            "robust benchmark",
            "never proof of superiority",
            "",
            "implemented",
        ),
        _row(
            "Inverse Volatility",
            "portfolio",
            "returns matrix",
            "weights",
            "risk-adjusted metrics",
            "risk scaling baseline",
            "return maximization alone",
            "",
            "implemented",
        ),
        _row(
            "Min Variance",
            "portfolio",
            "returns/covariance",
            "weights",
            "volatility/drawdown",
            "defensive allocation",
            "unstable covariance",
            "scipy",
            "implemented",
        ),
        _row(
            "Max Sharpe",
            "portfolio",
            "returns/covariance",
            "weights",
            "Sharpe",
            "diagnostic optimizer",
            "weak expected returns",
            "scipy",
            "implemented",
        ),
        _row(
            "HRP",
            "portfolio",
            "returns/correlation",
            "weights",
            "risk/drawdown",
            "cluster risk allocation",
            "highest-return claim",
            "",
            "implemented",
        ),
        _row(
            "Risk Parity",
            "portfolio",
            "returns/covariance",
            "weights",
            "risk contribution",
            "balanced risk",
            "equity alpha claim",
            "scipy",
            "implemented",
        ),
        _row(
            "Min CVaR",
            "portfolio",
            "returns matrix",
            "weights",
            "CVaR/drawdown",
            "tail-aware defensive allocation",
            "normal-only assumption",
            "scipy",
            "implemented",
        ),
        _row(
            "Black-Litterman",
            "portfolio",
            "returns/covariance/market caps",
            "weights",
            "portfolio metrics",
            "market-cap prior exists",
            "missing market caps",
            "",
            "blocked",
        ),
        _row(
            "Robust Optimization",
            "portfolio",
            "uncertainty sets",
            "weights",
            "robust utility",
            "institutional robust allocation",
            "not enough uncertainty validation",
            "",
            "not_implemented",
        ),
        _row(
            "Convex Optimization",
            "portfolio",
            "objective/constraints",
            "weights",
            "objective value",
            "well-defined convex objective",
            "nonconvex hidden assumptions",
            "scipy/cvx optional",
            "partially_implemented",
        ),
        _row(
            "Cluster-balanced",
            "portfolio",
            "returns/correlation clusters",
            "weights",
            "cluster exposure",
            "diversification control",
            "clusters unstable",
            "sklearn/scipy",
            "implemented",
        ),
        _row(
            "Random portfolio benchmark",
            "portfolio benchmark",
            "returns matrix",
            "random portfolios",
            "percentile",
            "robustness comparator",
            "proof of future return",
            "",
            "implemented",
        ),
        _row(
            "Random Walk benchmark",
            "time series",
            "returns history",
            "forecast",
            "forecast error",
            "baseline forecast",
            "allocation proof",
            "",
            "implemented",
        ),
        _row(
            "ARMA",
            "time series",
            "stationary univariate series",
            "forecast",
            "AIC/BIC/error",
            "short-memory diagnostics",
            "nonstationary raw prices",
            "statsmodels",
            "optional",
        ),
        _row(
            "ARIMA",
            "time series",
            "univariate series",
            "forecast",
            "AIC/BIC/error",
            "benchmark forecast",
            "large universe blind run",
            "statsmodels",
            "optional",
        ),
        _row(
            "SARIMA",
            "time series",
            "seasonal univariate series",
            "forecast",
            "AIC/BIC/error",
            "seasonality evidence",
            "daily assets without seasonality",
            "statsmodels",
            "not_appropriate",
        ),
        _row(
            "GARCH",
            "volatility",
            "returns series",
            "volatility forecast",
            "vol forecast error",
            "risk forecasting",
            "direct return forecast",
            "arch optional",
            "optional",
        ),
        _row(
            "Linear Regression",
            "regression",
            "features/target",
            "forecast",
            "RMSE/MAE/R2",
            "interpretable baseline",
            "nonlinear alpha claim",
            "sklearn",
            "implemented",
        ),
        _row(
            "Ridge",
            "regression",
            "features/target",
            "forecast",
            "RMSE/MAE/R2",
            "regularized baseline",
            "unsupported nonlinearity",
            "sklearn",
            "implemented",
        ),
        _row(
            "Lasso",
            "regression",
            "features/target",
            "forecast",
            "RMSE/MAE/R2",
            "sparse linear features",
            "unstable feature set",
            "sklearn",
            "optional",
        ),
        _row(
            "Decision Tree",
            "regression/classification",
            "features/target",
            "forecast/class",
            "RMSE/AUC/F1",
            "diagnostic nonlinear baseline",
            "overfit-prone small samples",
            "sklearn",
            "implemented",
        ),
        _row(
            "Random Forest",
            "regression/classification",
            "features/target",
            "forecast/class",
            "RMSE/AUC/F1",
            "nonlinear benchmark",
            "black-box promotion without validation",
            "sklearn",
            "implemented",
        ),
        _row(
            "Gradient Boosting",
            "regression/classification",
            "features/target",
            "forecast/class",
            "RMSE/AUC/F1",
            "nonlinear benchmark",
            "overfit without nested validation",
            "sklearn",
            "implemented",
        ),
        _row(
            "XGBoost optional",
            "regression/classification",
            "features/target",
            "forecast/class",
            "RMSE/AUC/F1",
            "if dependency available",
            "mandatory dependency",
            "xgboost",
            _optional("xgboost"),
        ),
        _row(
            "LSTM/RNN optional",
            "deep learning",
            "large sequential data",
            "forecast",
            "test error",
            "research only with strict validation",
            "small sample direct allocation",
            "tensorflow",
            _optional("tensorflow"),
        ),
        _row(
            "Logistic Regression",
            "classification",
            "features/downside label",
            "probability",
            "ROC AUC/PR AUC/F1/Brier",
            "downside diagnostic",
            "direct buy signal",
            "sklearn",
            "implemented",
        ),
        _row(
            "PCA",
            "dimension reduction",
            "returns/features",
            "components",
            "explained variance",
            "factor compression",
            "standalone alpha proof",
            "sklearn",
            "implemented",
        ),
        _row(
            "Factor model",
            "factor",
            "factors/exposures",
            "risk model",
            "tracking/error",
            "institutional risk decomposition",
            "no factor data",
            "",
            "not_implemented",
        ),
        _row(
            "Reinforcement Learning",
            "allocation research",
            "simulator/reward/constraints",
            "policy",
            "OOS utility",
            "research sandbox only",
            "production allocation",
            "",
            "not_appropriate",
        ),
    ]
    return pd.DataFrame(rows)


def _row(
    model: str,
    task_type: str,
    input_requirements: str,
    output: str,
    metric: str,
    when_appropriate: str,
    when_not_appropriate: str,
    dependencies: str,
    status: str,
) -> dict[str, str]:
    return {
        "model": model,
        "task_type": task_type,
        "input_requirements": input_requirements,
        "output": output,
        "metric": metric,
        "when_appropriate": when_appropriate,
        "when_not_appropriate": when_not_appropriate,
        "required_dependencies": dependencies,
        "current_status": status,
    }


def _optional(package: str) -> str:
    return (
        "optional_available"
        if importlib.util.find_spec(package)
        else "optional_not_available"
    )
